"""Trains the fraud-detection model on synthetic data.

There is no real fraud-labeled dataset for a portfolio project, and none is
faked to look like one -- every transaction and label here is generated by
this script, from a deliberately simple heuristic (elevated velocity, high
amount, and merchant-diversity outliers weighted toward fraud, plus noise).
Enough signal for the model to learn something real and for reason codes to
mean something; not a claim of production-grade fraud modeling. See
ADR-0009.

Usage:
    uv run --package fraudguard-ml python ml/pipelines/train.py
    uv run --package fraudguard-ml python ml/pipelines/train.py --samples 50000 --seed 1
"""

from __future__ import annotations

import argparse
import shutil
from datetime import UTC, datetime
from pathlib import Path

import lightgbm as lgb
import numpy as np

from fraudguard_ml import FEATURE_NAMES, save_model

_REPO_ROOT = Path(__file__).resolve().parents[2]
_DEFAULT_MODEL_PATH = _REPO_ROOT / "ml" / "models" / "fraud_model.txt"
_DEFAULT_METADATA_PATH = _REPO_ROOT / "ml" / "models" / "fraud_model.meta.json"
# Milestone 26: fraud_model.txt/fraud_model.meta.json are the single
# fixed-path pair model-service actually reads (LocalModelArtifactSettings)
# -- always "whatever was trained most recently", overwritten every run,
# unchanged here since a serving process reading "latest" from a fixed
# path is correct runtime behavior. _DEFAULT_HISTORY_DIR is additive: a
# per-version copy retained alongside, so a previous run's exact model
# file and metadata (including the seed/n_samples that reproduce it) are
# not silently lost the way they were before this milestone. Both stay
# under ml/models/, already entirely gitignored (.gitignore) -- this
# milestone does not change what gets committed, only what's retained
# locally/in CI between runs.
_DEFAULT_HISTORY_DIR = _REPO_ROOT / "ml" / "models" / "history"

_DEFAULT_SAMPLE_COUNT = 20_000
_VALIDATION_FRACTION = 0.2
# Fraud is rare -- landing near a realistic single-digit percent keeps the
# class imbalance real instead of training on an artificial 50/50 split.
_FRAUD_QUANTILE = 0.96


def _generate_synthetic_dataset(
    n: int, rng: np.random.Generator
) -> tuple[np.ndarray, np.ndarray]:
    """Generate `n` synthetic (features, label) rows.

    Two account archetypes: most accounts ("normal", ~90%) transact
    infrequently across few merchants; a minority ("bursty", ~10%) have
    elevated velocity and merchant diversity -- the kind of pattern
    account-takeover fraud tends to produce. Fraud is drawn more often from
    the bursty archetype and from high-value transactions, but never
    deterministically from either alone -- normal accounts can still
    produce a fraudulent transaction and bursty accounts are still usually
    legitimate, or the model would learn a trivial rule instead of a real
    one.
    """
    is_bursty = rng.random(n) < 0.10

    velocity_1m = rng.poisson(np.where(is_bursty, 3.0, 0.1))
    velocity_1h = velocity_1m + rng.poisson(np.where(is_bursty, 8.0, 0.5))
    velocity_24h = velocity_1h + rng.poisson(np.where(is_bursty, 20.0, 2.0))
    distinct_merchants_24h = np.minimum(
        velocity_24h, rng.poisson(np.where(is_bursty, 6.0, 1.0)) + 1
    )
    amount = rng.lognormal(mean=np.where(is_bursty, 4.5, 3.5), sigma=1.0)

    risk_score = (
        0.35 * np.clip(velocity_1m / 5.0, 0, 1)
        + 0.20 * np.clip(velocity_1h / 15.0, 0, 1)
        + 0.15 * np.clip(distinct_merchants_24h / 8.0, 0, 1)
        + 0.20 * np.clip(amount / 1000.0, 0, 1)
        + 0.10 * is_bursty
        + rng.normal(0, 0.15, n)  # noise -- nothing here is deterministic
    )
    label = (risk_score > np.quantile(risk_score, _FRAUD_QUANTILE)).astype(int)

    features = np.column_stack(
        [amount, velocity_1m, velocity_1h, velocity_24h, distinct_merchants_24h]
    )
    return features, label


def _roc_auc(y_true: np.ndarray, y_score: np.ndarray) -> float:
    """AUC via the rank-sum (Mann-Whitney U) identity, to avoid a
    scikit-learn dependency for one metric. Ties are not rank-averaged --
    acceptable here since `y_score` is continuous synthetic data where
    exact ties are effectively impossible.
    """
    order = np.argsort(y_score)
    ranks = np.empty(len(y_score), dtype=float)
    ranks[order] = np.arange(1, len(y_score) + 1)
    n_pos = int(y_true.sum())
    n_neg = len(y_true) - n_pos
    if n_pos == 0 or n_neg == 0:
        return float("nan")
    sum_ranks_pos = ranks[y_true == 1].sum()
    return float((sum_ranks_pos - n_pos * (n_pos + 1) / 2) / (n_pos * n_neg))


def train(
    *,
    n_samples: int = _DEFAULT_SAMPLE_COUNT,
    seed: int = 0,
    model_path: Path = _DEFAULT_MODEL_PATH,
    metadata_path: Path = _DEFAULT_METADATA_PATH,
    history_dir: Path = _DEFAULT_HISTORY_DIR,
) -> None:
    rng = np.random.default_rng(seed)
    features, labels = _generate_synthetic_dataset(n_samples, rng)

    split = int(n_samples * (1 - _VALIDATION_FRACTION))
    x_train, x_val = features[:split], features[split:]
    y_train, y_val = labels[:split], labels[split:]

    train_set = lgb.Dataset(x_train, label=y_train, feature_name=list(FEATURE_NAMES))
    val_set = lgb.Dataset(x_val, label=y_val, reference=train_set)

    params = {
        "objective": "binary",
        "metric": "auc",
        "verbosity": -1,
        "num_leaves": 31,
        "learning_rate": 0.05,
        "is_unbalance": True,
        "seed": seed,
    }

    booster = lgb.train(
        params,
        train_set,
        num_boost_round=200,
        valid_sets=[val_set],
        callbacks=[lgb.early_stopping(stopping_rounds=20, verbose=False)],
    )

    val_predictions = np.asarray(
        booster.predict(x_val, num_iteration=booster.best_iteration)
    )
    auc = _roc_auc(y_val, val_predictions)

    version = f"fraud-lgbm-{datetime.now(UTC):%Y%m%d-%H%M%S}"
    metadata = save_model(
        booster,
        model_path,
        metadata_path,
        version=version,
        auc=auc,
        seed=seed,
        n_samples=n_samples,
    )

    # Retain a per-version copy alongside the fixed-path pair -- see
    # _DEFAULT_HISTORY_DIR's own comment for why this exists.
    history_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(model_path, history_dir / f"{metadata.version}.txt")
    shutil.copy2(metadata_path, history_dir / f"{metadata.version}.meta.json")

    print(f"trained {metadata.version}")
    print(f"  samples: {n_samples} (fraud rate {labels.mean():.2%})")
    print(f"  seed: {seed}")
    print(f"  validation AUC: {auc:.4f}")
    print(f"  model:    {model_path}")
    print(f"  metadata: {metadata_path}")
    print(f"  history:  {history_dir / metadata.version}.{{txt,meta.json}}")


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--samples", type=int, default=_DEFAULT_SAMPLE_COUNT)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--model-path", type=Path, default=_DEFAULT_MODEL_PATH)
    parser.add_argument("--metadata-path", type=Path, default=_DEFAULT_METADATA_PATH)
    parser.add_argument("--history-dir", type=Path, default=_DEFAULT_HISTORY_DIR)
    return parser.parse_args()


if __name__ == "__main__":
    args = _parse_args()
    train(
        n_samples=args.samples,
        seed=args.seed,
        model_path=args.model_path,
        metadata_path=args.metadata_path,
        history_dir=args.history_dir,
    )
